version: "3.9"
services:
    nginx-debian:
        build:
            context: ./infrastructure/development/docker/nginx-debian
            dockerfile: Dockerfile
        ports:
            -   "80:80"
        volumes:
            -   ./:/system-prototype
        depends_on:
            -   php-fpm-debian

    php-fpm-debian:
        build:
            context: ./infrastructure/development/docker/php-fpm-debian
            dockerfile: Dockerfile
        environment:
            APPLICATION_ENVIRONMENT: development
            APPLICATION_DEBUG: 1
            MYSQL_HOST: mysql-debian
            MYSQL_PORT: 3306
            MYSQL_USER: system-prototype
            MYSQL_PASSWORD: system-prototype
            MYSQL_DATABASE: system-prototype
            MYSQL_CHARSET: utf8
            MYSQL_DRIVER: pdo_mysql
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: test
            MAILER_PASSWORD: test
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: test@test.test
            FRONTEND_URL: http://127.0.0.1
        volumes:
            - ./:/system-prototype

    php-cli-debian:
        build:
            context: ./infrastructure/development/docker/php-cli-debian
            dockerfile: Dockerfile
        environment:
            APPLICATION_ENVIRONMENT: development
            APPLICATION_DEBUG: 1
            MYSQL_HOST: mysql-debian
            MYSQL_PORT: 3306
            MYSQL_USER: system-prototype
            MYSQL_PASSWORD: system-prototype
            MYSQL_DATABASE: system-prototype
            MYSQL_CHARSET: utf8
            MYSQL_DRIVER: pdo_mysql
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: test
            MAILER_PASSWORD: test
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: test@test.test
            FRONTEND_URL: http://127.0.0.1
        volumes:
            - ./:/system-prototype

    mysql-debian:
        image: mysql:8.0
        environment:
            MYSQL_USER: system-prototype
            MYSQL_PASSWORD: system-prototype
            MYSQL_ROOT_PASSWORD: system-prototype
            MYSQL_DATABASE: system-prototype
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
volumes:
    mysql: